version: '3.9'

services:
  backend:
    build:
      context: .
    container_name: backend-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@localhost:5432/api
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: