name: Backend Integration Tests

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest

    # --- DEFINIR VARIÁVEIS DE AMBIENTE NO NÍVEL DO JOB ---
    # Isso garante que SECRET_KEY e outras variáveis estejam disponíveis
    # para todas as etapas do job, incluindo quando o Python importa módulos
    # e inicializa a classe Settings.
    env:
      # Use DATABASE_URL para 'api_test' para os testes, conforme o erro indica.
      # Se seu backend precisa de 'api' para iniciar, você pode sobrescrever
      # essa variável no passo 'Start backend to create tables' se necessário.
      DATABASE_URL: postgresql+asyncpg://hiveuser:hive123@localhost:5432/api
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: hiveuser
          POSTGRES_PASSWORD: hive123
          POSTGRES_DB: api # Use api_test aqui para o serviço PostgreSQL
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U hiveuser -d api_test" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v4
        with:
          repository: TeamHiveAPI/API-2025.01-BACK
          ref: main
          path: backend

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.10"

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest # Garante pytest instalado

      - name: Wait for PostgreSQL
        run: sleep 10

      - name: Start backend to create tables
        working-directory: backend
        env:
          # Se o seu backend precisa de um DB diferente para iniciar (ex: 'api' vs 'api_test'),
          # você pode sobrescrever DATABASE_URL aqui. Caso contrário, ele usará a do job.
          DATABASE_URL: postgresql+asyncpg://hiveuser:hive123@localhost:5432/api # Exemplo se precisar de 'api' para iniciar
          # As outras variáveis já vêm do nível do job
        run: |
          # Inicia o Uvicorn em segundo plano
          # E espera um pouco para dar tempo do app iniciar e criar as tabelas
          python -m uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 15 # Dê um tempo suficiente para o create_tables_async() rodar

      - name: Run backend tests
        working-directory: backend
        
        run: pytest