name: Backend Integration Tests

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: hiveuser
          POSTGRES_PASSWORD: hive123
          POSTGRES_DB: api
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U hiveuser -d api" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v4
        with:
          repository: TeamHiveAPI/API-2025.01-BACK
          ref: main
          path: backend

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.10"

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest # Garante pytest instalado

      - name: Wait for PostgreSQL
        run: sleep 10

      - name: Start backend to create tables
        working-directory: backend
        env:
          # É crucial que todas as variáveis de ambiente que seu backend precisa
          # para iniciar e se conectar ao DB estejam aqui.
          DATABASE_URL: postgresql+asyncpg://hiveuser:hive123@localhost:5432/api
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
          REFRESH_TOKEN_EXPIRE_DAYS: 7
        run: |
          # Inicia o Uvicorn em segundo plano
          # E espera um pouco para dar tempo do app iniciar e criar as tabelas
          python -m uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 15 # Dê um tempo suficiente para o create_tables_async() rodar

      - name: Run backend tests
        working-directory: backend
        env:
          # As variáveis de ambiente também precisam estar aqui para os testes.
          DATABASE_URL: postgresql+asyncpg://hiveuser:hive123@localhost:5432/api
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
          REFRESH_TOKEN_EXPIRE_DAYS: 7
        run: pytest
