name: CI Backend (Windows Runner)

on:
  push:
    branches: [ main, develop ]    # Executa nos pushes para 'main' e 'develop'
  pull_request:
    branches: [ main, develop ]    # Executa nos PRs com destino a 'main' ou 'develop'

jobs:
  unit-tests:
    name: Testes Unitários
    runs-on: windows-latest        # Runner Windows

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4   # Faz o checkout do repositório

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'    # Define a versão do Python

      - name: Instalar dependências do projeto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # No Windows não há apt; as libs nativas devem vir como wheels ou via psycopg2-binary

      - name: Rodar testes unitários com pytest
        run: pytest tests/unit/     # Executa testes na pasta tests/unit

  integration-tests:
    name: Testes de Integração
    runs-on: windows-latest        # Runner Windows

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4   # Faz o checkout do repositório

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'    # Define a versão do Python

      - name: Instalar dependências do projeto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes de integração com pytest
        run: pytest tests/integration/  # Executa testes na pasta tests/integration
