name: Backend CI

on:
  push:
    branches: [ main, develop ]    # Executa nos pushes para 'main' e 'develop'
  pull_request:
    branches: [ main, develop ]    # Executa nos PRs com destino a 'main' ou 'develop'

jobs:
  unit-tests:
    name: Testes Unitários
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: api
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências de sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências do projeto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes unitários com pytest
        run: pytest tests/unit/

  integration-tests:
    name: Testes de Integração
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: api
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências de sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências do projeto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes de integração com pytest
        run: pytest tests/integration/
