name: CD - Deploy para Homologação

on:
  push:
    branches: [ homolog ]

jobs:
  deploy-homolog:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run security checks
      run: |
        pip install bandit safety
        bandit -r . -x tests/
        safety check
        
    - name: Deploy to Azure Homologation
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'api-weather-homolog'
        publish-profile: ${{ secrets.AZURE_HOMOLOG_PUBLISH_PROFILE }}
        package: .
        
    - name: Run smoke tests
      run: |
        pip install requests
        python scripts/smoke_tests.py --env=homolog
