name: Publicar Imagem Docker no Docker Hub

on: 
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: erikadias/fatec-2025.01
  DOCKER_IMAGE_TAG: latest

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Definir tags da imagem
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.DOCKER_IMAGE_TAG }}
            type=sha,format=short

      - name: Construir e enviar a imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ../Dockerfile
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verificação de sucesso
        run: echo "Imagem ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} foi enviada para o Docker Hub com sucesso!"