name: Testes Automatizados

on:
  pull_request:
    branches: [ develop ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    # Configura um container com PostgreSQL para testes
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: teste_user       # ← Usuário do banco de testes
          POSTGRES_PASSWORD: teste_pass  # ← Senha do banco de testes
          POSTGRES_DB: teste_db          # ← Nome do banco de testes
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    # 1. Baixa o código do repositório
    - name: Checkout
      uses: actions/checkout@v3

    # 2. Configura Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. Instala dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx sqlalchemy asyncpg

    # 4. Configura variáveis de ambiente (DATABASE_URL para testes)
    name: Setup environment
    run: |
      echo "DATABASE_URL=postgresql+asyncpg://test_user:test_pass@localhost:5432/test_db" >> $GITHUB_ENV

    # 5. Roda os testes
    - name: Run testes
      run: |
        pytest -v testes/